name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # Reuse existing CI workflow
  ci:
    uses: ./.github/workflows/ci.yml

  # Create release after CI passes
  release:
    needs: ci # This ensures CI passes before creating release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
